### PR TITLE
Adding container template generator

### PR DESCRIPTION
**Pull request by Goroner**
This is only soy template for container

### CODE REVIEW

**Comment by Goroner** [comment]
#89

**Comment by GewenBB** [comment]
@Goroner Please see my notes in the commits. Once those are fixed I think this will be good to go.

**Comment by Goroner** [comment]
Sure, I will fix them right now

**Comment by Goroner** [comment]
@GewenBB For the length I thought at least 2 chars, as there's no specification for the number of characters. I think it's not good idea to have component with name of length 1?

**Comment by Goroner** [comment]
@GewenBB I added comment for the regexp. Check that and report back. The length of the names is at least 2, it was intentionally set like that because I think name with length 1 is not appropriate. If you think that names with length 1 are fine just ping me back I will update it.

**Comment by Gabs00** [comment]
@Goroner 

I personally see no issue with it being atleast 1, however I will defer to @craigwalkeruk 

Also, on the regex, the i modifier is not need as spaces do not have case

**Comment by mistermark** [comment]
If I can chime in here, @Gabs00 & @Goroner, I'd rather see at least 2 or more characters for a name. It just doesn't make sense to give something a name of 1 character.

**Pull request merged**
