### PR TITLE
Lp12 fixes

### PR DESCRIPTION
**Pull request by stephanepericat**
Hi @operatino ,

I made some small fine tunings for the lp12 widget and module templates to be production-ready:

 - added config xml file for widget
 - point index.html to proper js / css folders
 - remove dist folder from template which is generated by the bb-lp build command
 - fix template variable parsing in css files

### CODE REVIEW

**Comment by operatino** [comment]
Why you removed `index.dev.html`? It's for standalone development and styleguide.

**Comment by stephanepericat** [comment]
Because they removed the `start` command from the **bb-lp-cli** and have no plan on bringing it back anytime soon according to the meeting I had yesterday with Dragosh and Ben. We can always bring back the feature whenever it's available again. Also, in the LP12 archetype, the styleguide works without it, by simply using the run script at the root of the styleguide folder.

**Comment by stephanepericat** [comment]
I put index.dev.html back in the template

**Comment by stephanepericat** [comment]
I mostly care about adding the yapi import file tbh

**Comment by operatino** [comment]
`index.dev.html` is used by styleguide to show rendered widget examples. It's not yet well documented, but LP UI bundle is using it actively. Do you plan yo do any other changes? I will accept PR and release latest changes a bit later this week.

**Comment by stephanepericat** [comment]
No it should be fine; as I said, it was mostly about adding the import xml file and removing the dist/ folders generated by the lp cli. Thanks!

**Pull request merged**
