### PR TITLE
Removes test folder and "shortcuts"

### PR DESCRIPTION
**Pull request by GuilhermeMedeiros**
If bb archetype or bb install is too long, a simple alias on the terminal should solve the problem

### CODE REVIEW

**Comment by operatino** [comment]
Even simple alias requires some configuration, and having a bunch of tools in use, together this will spawn a decent amount of work. NPM and Bower both have default shortcuts for install, and it's a normal practice.

BTW, PR title says one, but code diff contains other changes which is `bbmodel` clean up.

**Comment by GuilhermeMedeiros** [comment]
NPM and bower are highly focused on the install command. If we gonna create one shortcut per command we gonna end up with a mess. 
The title says "removes" test folder, and of course everything that is inside. As you can see on the diff.

**Comment by operatino** [comment]
It's not a mess, as well as with short version of CLI arguments. And if it doesn't require any support, why bother?

**Comment by GuilhermeMedeiros** [comment]
ES, LP and CXP are all gonna use the same CLI. The less commands we have on this folder the better.

**Comment by igord** [comment]
Anyway, we will soon move away from Ronin probably to cliparse where it is easy to create aliases for commands programmatically.

**Pull request merged**
