### PR TITLE
Feature/export import update

### PR DESCRIPTION
**Pull request by igord**

### CODE REVIEW

**Comment by operatino** [comment]
Please check the tests, they're failing now. And let me know, when you finish working on this. I will review only when it's done.

**Comment by operatino** [comment]
Do we need this huge XML output on export?

image

**Comment by operatino** [comment]
Both these commands does not prettify (format) XML output

```
bb export --save portal1.xml
bb export --save portal1.xml --pretty
```

**Comment by operatino** [comment]
Where's logic behind short `-k` flag for long `--chunk`?

**Comment by operatino** [comment]
Why `bb import` don't have any glob by dafault? Previously it was `*.xml`.

**Comment by operatino** [comment]
error on `bb import`:

```
robert-bb:test-new-import robert $ bb import -t portal.xml
TypeError: Cannot read property 'statusCode' of undefined
    at parseResponse (/Users/robert/Dropbox/Project/all/backbase-cli/node_modules/mosaic-rest-js/dist/node/mosaic-rest-js.js:341:31)
    at Request._callback (/Users/robert/Dropbox/Project/all/backbase-cli/node_modules/mosaic-rest-js/dist/node/mosaic-rest-js.js:386:13)
    at self.callback (/Users/robert/Dropbox/Project/all/backbase-cli/node_modules/mosaic-rest-js/node_modules/request/request.js:372:22)
    at Request.emit (events.js:129:20)
    at Request.onRequestError (/Users/robert/Dropbox/Project/all/backbase-cli/node_modules/mosaic-rest-js/node_modules/request/request.js:970:8)
    at ClientRequest.emit (events.js:107:17)
    at Socket.socketErrorListener (_http_client.js:271:9)
    at Socket.emit (events.js:129:20)
    at net.js:459:14
    at process._tickCallback (node.js:355:11)
```

**Comment by operatino** [comment]
@craigwalkeruk, what do you think about these file-names in chunked export?

image

Having three places with widgets is a bit confusing - `widgets.xml` (widget instances), `server-widgets.xml`, `portal-widgets.xml`. I would at least rename the first one.

**Comment by operatino** [comment]
After exporting to zip, I get file which is impossible to unzip :)

```
bb export --save retail.zip
```

I just recursively get `retail.zip.cpgz`.

**Comment by igord** [comment]
- default bb export is returning xml string in case that you want to pipe the output
- when output is not chunked it just saves raw xml file, like orchestrator export does(--type portal)
- chunked shortcut is -k because -c is already used and chunK ends with k
- if bb import works with xmls only, *.xml could be logical default, but it can also import zip and dir
- please provide your portal.xml for debugging
- chunked export file names are made from names of the groups that orchestrator is returning
- zip is only valid if --type is not model(default)

**Comment by operatino** [comment]
> default bb export is returning xml string in case that you want to pipe the output

default should be the most used one, which is output file with default name

> chunked shortcut is -k because -c is already used and chunK ends with k

omg... okay

> if bb import works with xmls only, *.xml could be logical default, but it can also import zip and dir

currently it works only with zip

> please provide your portal.xml for debugging

here it is http://d.pr/f/182QD

> chunked export file names are made from names of the groups that orchestrator is returning

it doesn't mean we should follow it

> zip is only valid if --type is not model(default)

why do you export broken zip in first time? let's then define `portal` as default type

**Comment by igord** [comment]
> default bb export is returning xml string in case that you want to pipe the output  
> > default should be the most used one, which is output file with default name

But what to output? What is the most used one? Model xml, model xml chunked, full export as zip or full export chunked?

> when output is not chunked it just saves raw xml file, like orchestrator export does(--type portal)
> > I think it still should be prettified in this case

Then orchestrator raw export(zip) should be prettified and sorted also?

> if bb import works with xmls only, *.xml could be logical default, but it can also import zip and dir
> > currently it works only with zip

No. It exports xml, zip and dir :8ball: 

> zip is only valid if --type is not model(default)
> > why do you export broken zip in first time? let's then define `portal` as default type

It is not broken zip but xml file that you saved with zip extension : )
--type portal requires orchestrator and contentservices to run so I wouldn't make it default

**Comment by igord** [comment]
@operatino Regarding your portal.xml file, server is rejecting it. Maybe because xml declaration is missing or it is not formatted well? I updated error reporting so it is more meaningful for those kind of cases now.

**Comment by operatino** [comment]
`bb export` is not passing `-c` prop (maybe other as well):

```
robert-bb:test-import-final robert $ bb export -c '/'
unclosed xml attribute
@#[line:8,col:29]
✖ bb export: Cannot read property 'portal' of undefined
```

I'm trying this on project with changed context (degroof). With `.bbrc` defined works fine.

**Comment by operatino** [comment]
Merged it into `0.2.0-beta` branch, and release under same version. 

Since latest stable is 0.1.6, to install beta run

```
npm i bb-cli@0.2.0-beta -g
```

**Pull request closed without merging**
